title          : "Introduction to DataCamp Projects"
description    : >
  This project is an introduction to DataCamp Projects. 
language       : python
from           : 'python-notebooks-prod:56'
runtime_config : default
state          : live
long_description: |
  In this project, you will get a gentle introduction to DataCamp Projects. We will
  walk you through the projects interface interactively. You will learn how
  to work with jupyter notebooks, complete tasks, check your work, and successfully
  finish your project!
technology: 2
instructors:
  - ramnath@datacamp.com
collaborators:
  - martijn@datacamp.com
topics:
  - 8
  - 4
  - 3
time_needed: "45 minutes"
illustration: "https://projects.datacamp.com/assets/images/R@2X.png"

